### ISSUE TITLE
コードの説明をする

### ISSUE THREAD

**Issue by kawano-020** [TakumiUemoto/yoku-test-b#1]
以下のコードを文章で説明してほしい！
[src/components/TodoList.js](https://github.com/TakumiUemoto/yoku-test-b/blob/main/src/components/TodoList.js)

```jsx
<ul>
    {todo.map((text, index) => (
    <Li key={ index }>
        <DeleteButton
        onClick={() => {handleRemoveTask(index);}}>
            X
        </DeleteButton>
        {text.task}
    </Li>
    ))}
</ul>
```

**Comment by TakumiUemoto** [comment]
useStateに格納されたtodo（オブジェクト配列）に対してmapメソッドを適用し、各要素をkey属性がindexに設定されたli要素をテキストとして表示する。
*todoのプロパティであるtaskを呼び出し、liのテキスト部分として表示している。

その+要素としてtaskの前に削除ボタンを配置することで、各リストにボタンも一緒に表示される仕組みになっている。
